### ISSUE TITLE
Wrong check for configuration existence using array_key_exists()

### ISSUE THREAD

**Issue by GameplayJDK** [thephpleague/flysystem#1201]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.0.46

#### Summary

I encountered this when using `league/flysystem` (1.0.46) with the available `league/flysystem-bundle` (1.5.0).

In my opinion the `get()` method of the `Config` should not use `array_key_exists()`, but `isset()` instead, to determine if the default value should be used.

```php
    public function get($key, $default = null)
    {
        if ( ! array_key_exists($key, $this->settings)) {
            return $this->getDefault($key, $default);
        }

        return $this->settings[$key];
    }
```

The default value for `visibility` defined in my configuration is `null` (through the symfony bundle). So the default is retrieved like this, where the default given as argument is `null` and the default from the fallback config is also `null`.

```php
    protected function getDefault($key, $default)
    {
        if ( ! $this->fallback) {
            return $default;
        }

        return $this->fallback->get($key, $default);
    }
```

This is related to this [issue](https://github.com/thephpleague/flysystem-bundle/issues/54).

#### How to reproduce

When a default is defined for, in my case `'visibility' => null,`, and `createDir()` is called, the error thrown is an `index not found` with and empty index.

That's caused by the way the check is made. With `array_key_exists()` null values are allowed, but for `visibility`, that is not allowed, since it is used as an index, which naturally cannot be found. An example from `createDir()` from the `local` adapter:

```php
        $visibility = $config->get('visibility', 'public');

        if ( ! is_dir($location) && ! mkdir($location, $this->permissionMap['dir'][$visibility], true)) { // <- So $visbility is null here.
```

The error:

```
Uncaught PHP Exception ErrorException: "Notice: Undefined index: " at D:\Project\example\vendor\league\flysystem\src\Adapter\Local.php line 368
```

The documentation does not state what options are required. To my understanding, no options are required, since the `get()` receives a default, but prefers the default from the fallback configuration which contains `'visibility' => null,`.

**Comment by frankdejonge** [comment]
Hi, why are you using the null value? Can't you omit the value or use another default?

**Comment by GameplayJDK** [comment]
I used this with the bundle, where the default value is `null`, if not configured otherwise. See the linked issue for that matter.

Since I don't pass an explicit configuration array to [`createDir($dirname, array $config = [])`](https://github.com/thephpleague/flysystem/blob/1.x/src/Filesystem.php#L258), the call to [`prepareConfig()`](https://github.com/thephpleague/flysystem/blob/1.x/src/Filesystem.php#L261) will return a `Config` object with no values, but containing a fallback `Config` object. That fallback configuration holds the values, in this case defined by the bundle configuration defaults. It could happen with any fallback configuration given, that a value becomes `null`.
So when the `Local` adapter in this case is trying to get the `visibility` value from the permission map ([source](https://github.com/thephpleague/flysystem/blob/1.x/src/Adapter/Local.php#L384)), it receives a default of `public`. That default will never be returned, since the fallback config contains the `visibility` key (with a value of `null`). And `null` is no valid key to be used with that permission map.

The problem I see with using `array_key_exists()` is, that `null` values are allowed, as said. In cases like the one described above, where an array key is retrieved, a `null` value should not be allowed as return value, but the provided default in the `get()` method call should be used instead.

So either the bundle configuration default is invalid or the logic of getting fallback values is prone to such errors.

**Comment by frankdejonge** [comment]
This should be fixed in the bundle.

**Comment by GameplayJDK** [comment]
The problem would still persist (kind of), when the visibility default is set to `null` manually or by an "explicit" configuration. As described in linked ticket, the default value to the yaml configuration class is/was `null`. When that is changed, the default is no longer `null`, so one is no longer forced to set a value on that, since the node is not explicitly required.

So the bundle side is fixed then, but in theory the configuration value can still be overridden manually through `Configuration::set()` and by that inject a null value. The local filesystem adapter makes use of `$this->permissionMap[$type][$visibility]`, where `$visibility` is nullable:

```php

    public function setVisibility($path, $visibility)
    {
        // ...

        $success = chmod($location, $this->permissionMap[$type][$visibility]);

        // ...
    }

    public function createDir($dirname, Config $config)
    {
        // ...

        $visibility = $config->get('visibility', 'public');

        if ( ! is_dir($location) && ! mkdir($location, $this->permissionMap['dir'][$visibility], true)) {

       // ...
    }

```

At that point, given the invalid value of `null` for the default visibility, this will result in a warning `Undefined array key` or something along that. See [this script](https://3v4l.org/XaijY) for reference.

I think some kind of null check could solve that issue easily. Either by raising an error/exception or falling back to a default default value.
