### ISSUE TITLE
Fallback to mimetype detection based on filename not working/present in v3

### ISSUE THREAD

**Issue by gdebrauwer** [thephpleague/flysystem#1442]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | n/a
| Version     | n/a

#### Summary

In v1, if the detected mimetype of a file was `application/octet-stream`, or `inode/x-empty`, or `application/x-empty`, then that detected mimetype would not be returned. Instead, the mimetype of the file would be detected based on its name

https://github.com/thephpleague/flysystem/blob/094defdb4a7001845300334e7c1ee2335925ef99/src/Adapter/Local.php#L325-L327

This causes an issue when trying to save a fake file with a specific mimetype, because the specific mimetype will never be returned. This makes it impossible to test code where validation is done based on the returned mimetype, because the fake file will always have the wrong mimetype

This issue was discovered when upgrading from Laravel 8 to 9 https://github.com/laravel/framework/issues/41916. 

#### How to reproduce

This can easily be reproduced in a new Laravel 9 project:
```php
Route::get('/', function () {
    // Fake file has mimetype "text/csv"
    dump($fakeFile = \Illuminate\Http\UploadedFile::fake()->create('test.csv', 123, 'text/csv'));

    dump($savedFilePath = Storage::put('tmp', $fakeFile));

    // Now the saved file does not have mimetype "text/csv" anymore. It is now "application/x-empty".
    // If you run this in a Laravel 8 project, you will get "text/csv" as mimetype.
    dump(Storage::mimetype($savedFilePath));
});
```

**Comment by frankdejonge** [comment]
Hi @gdebrauwer, I've transfered the issue to this repo since this is where it'll be fixed.

**Comment by frankdejonge** [comment]
This was fixed in 1.10.0. @gdebrauwer can you update the dependency and check if it works for you?

**Comment by gdebrauwer** [comment]
@frankdejonge I upgraded and I still get mimetype `application/x-empty` instead of `text/csv`

**Comment by gdebrauwer** [comment]
@frankdejonge It is because the `detectMimeTypeFromFile` method is used instead of the `detectMimeType` where you made a change. So I think the check of the `inconclusiveMimetypes` array should also be done in the `detectMimeTypeFromFile` method

**Comment by frankdejonge** [comment]
I'm going to fix this one slightly different, because users of this package outside of the flysystem context don't want changed behaviour.

**Comment by frankdejonge** [comment]
@gdebrauwer can you check if 3.0.16 of league/flysystem fixes it for you?

**Comment by gdebrauwer** [comment]
It works 🎉 Thanks a lot for the quick fix 🙂
