### ISSUE TITLE
Undefined offset: 8 when calling getContent()

### ISSUE THREAD

**Issue by divdax** [thephpleague/flysystem#229]
Hey,

the connection to the ftp and uploading files is working.
But when i call the getContent() method i get an error:

```
/var/www/pstool/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php
     * @param   string  $item
     * @param   string  $base
     * @return  array   normalized file array
     */
    protected function normalizeObject($item, $base)
    {
        $item = preg_replace('#\s+#', ' ', trim($item));
        list ($permissions, /* $number */, /* $owner */, /* $group */, $size, $month, $day, $time, $name) = explode(' ', $item, 9);
        $type = $this->detectType($permissions);
        $timestamp = strtotime($month . ' ' . $day . ' ' . $time);
```
The error is on line 259:
```
list ($permissions, /* $number */, /* $owner */, /* $group */, $size, $month, $day, $time, $name) = explode(' ', $item, 9);
```

I'm using v0.5.3. Any idea what's going wrong?

**Comment by frankdejonge** [comment]
This is fixed in dev-master (wil be released in 1.0.2). STAT is replaced with rawlist.

**Comment by GrahamCampbell** [comment]
@frankdejonge Better to recommend `~1.0@dev` rather than `dev-master`. `dev-master` is **always** a terrible idea.

**Comment by frankdejonge** [comment]
@GrahamCampbell I didn't recommend dev master, I recommended using the upcoming 1.0.2 if you need this.

**Comment by GrahamCampbell** [comment]
You said "This is fixed in dev-master". That's a version constraint. It's not the same as saying it's been fixed on the master branch, if you see what I mean. I don't want people to get confused.

**Comment by tianissimo** [comment]
@frankdejonge I tried dev-master and still get this error (Undefined offset: 8) when calling listContents(). 
Here is my $item dump:
```
string(46) "01-03-15 05:10PM 100641 testfile.xml" 
```
Will it be fixed on 1.0.2? or I need to write my own adapter.
Thank you.

**Comment by bogdanghervan** [comment]
I'm also getting this error (I'm using 1.0.15 here).

Here's my $item dump:
```
string(51) "drwxr-xr-x+   6 510             6 Aug  4  2011 2003"
```
The last "2013" is a directory name, but clearly I'm missing some of the parts that the normalization method expects.

Also, `ftp_systype()` returns `UNIX`.
