### ISSUE TITLE
timestamp & cache on creation bug

### ISSUE THREAD

**Issue by ctf0** [thephpleague/flysystem#947]
### Bug Report

>  "am not really sure what this table is for or means"

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | league/flysystem-cached-adapter (1.0.7)

#### Summary

when using a cache driver `ex.file` & trying to get the timestamp after creating **a new folder or uploading a new file**, you'll get an error because the cache doesnt wait for the retrieval of the item but rather it caches it on the spot.

#### How to reproduce
> for example using laravel "the issue is present even when creating a custom disk"

- enable caching https://laravel.com/docs/5.6/filesystem#caching
- create a new folder or upload a new file
- now try to retrieve the content with its meta-data `ex.$file['timestamp']` or better yet check the cached data directly

```js
// current "on creation"
"testing":{"path":"testing","dirname":"","basename":"testing","filename":"testing","type":"dir"}}

// good "after retrieval"
"testing":{"path":"testing","dirname":"","basename":"testing","filename":"testing","type":"dir","timestamp":1529550228}},
```

to fix the issue, the cache should only trigger on file retrieval "when using any of the list content methods", this way the cache is used only when the user actually read the file instead of using the cache as a 2nd storage disk.

**Comment by frankdejonge** [comment]
@ctf0 this is fixed in 1.0.9

**Comment by ctf0** [comment]
sadly its not, still getting error of `undefined index timestamp`

**Comment by ctf0** [comment]
@frankdejonge can u plz re-check this when u have time ?

**Comment by frankdejonge** [comment]
@ctf0 could you create a PR for it, I thought I had the test case done but you seem to hit an edge case I have trouble reproducing.

**Comment by ctf0** [comment]
can u give me the commit link where u fixed this issue, so i can re-test with

**Comment by frankdejonge** [comment]
I have a hard time following what you mean. Could you maybe link to the corresponding code? Getting the metadata is a best effort operation, if you need specific keys you should request them, it's not going to retrieve everything because that would be way to expensive in general.

**Comment by ctf0** [comment]
sure, its a package am building https://github.com/ctf0/Laravel-Media-Manager & using https://laravel.com/docs/5.6/filesystem#caching

- on folder creation i first make a call to create the folder https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/Controllers/Modules/NewFolder.php
- next i make another call to get the folder content https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/Controllers/Modules/GetContent.php#L53

and here is a [demo repo](https://github.com/ctf0/demos/tree/media-manager)
just enable https://github.com/ctf0/demos/blob/media-manager/config/filesystems.php#L54-L58 & check for the cache details under `storage/framework/cache`

**Comment by ctf0** [comment]
@frankdejonge any luck ? :balloon:
